version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/romm"
      - "/cleanuparr"
      - "/profilarr"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
